# Generated by Django 4.1.9 on 2023-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('temp', models.IntegerField()),
                ('condition', models.TextField()),
            ],
        ),
    ]
